### ISSUE TITLE
A clear guideline on how to setup Athena to run with Behat or Selenium.

### ISSUE THREAD

**Issue by iamstoick** [athena-oss/athena#31]
@rafaelspinto I witness the presentation of MC (from OLX Philippines) about Athena and I am really amazed of how this tool can do from a QA standpoint to DevOps. 

So I started to play after MC's presentation and the most obvious thing from the documentation is the setup. I am on Ubuntu and there is no clear guide on how to access the tool after running `apt-get install athena`. I tried `athena wizard star` but I am completely blind on that one.

Eager contributor here once I know how the system works.

**Comment by rafaelspinto** [comment]
Hi @geraldvillorente , great to hear that you like it :)

In order to be able to run behat with or without selenium, you need to install the following plugins : 

- [Plugin PHP](https://github.com/athena-oss/plugin-php)
- [Plugin Selenium](https://github.com/athena-oss/plugin-selenium)
- [Plugin Proxy](https://github.com/athena-oss/plugin-proxy) - This one is optional

you can use the `apt-get install athena-plugin-php athena-plugin-selenium athena-plugin-proxy` method or any other of the ones mentioned in the docs of those plugins.

Let me know how this works for you.

P.S.: Looking forward for your help and contribution 👍

**Comment by rafaelspinto** [comment]
Hi @geraldvillorente , was it useful?
